// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/xinghe903/chatify/offline/internal/biz"
	"github.com/xinghe903/chatify/offline/internal/conf"
	"github.com/xinghe903/chatify/offline/internal/data"
	"github.com/xinghe903/chatify/offline/internal/server"
	"github.com/xinghe903/chatify/offline/internal/service"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	messageRepo := data.NewOfflineMessageRepo(dataData, logger)
	offlineUsecase := biz.NewOfflineUsecase(messageRepo, logger)
	offlineService := service.NewOfflineService(offlineUsecase, logger)
	grpcServer := server.NewGRPCServer(bootstrap, offlineService, logger)
	httpServer := server.NewHTTPServer(bootstrap, offlineService, logger)
	client, err := data.NewEtcdClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	registrar := data.NewRegistry(client)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
