// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsOk(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OK.String() && e.Code == 200
}

func ErrorOk(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_OK.String(), fmt.Sprintf(format, args...))
}

// 消息重复
func IsMessageRepeat(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MESSAGE_REPEAT.String() && e.Code == 500
}

// 消息重复
func ErrorMessageRepeat(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_MESSAGE_REPEAT.String(), fmt.Sprintf(format, args...))
}

// 消息过期
func IsMessageExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MESSAGE_EXPIRED.String() && e.Code == 500
}

// 消息过期
func ErrorMessageExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_MESSAGE_EXPIRED.String(), fmt.Sprintf(format, args...))
}

// 校验签名失败
func IsPermissionDenied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PERMISSION_DENIED.String() && e.Code == 500
}

// 校验签名失败
func ErrorPermissionDenied(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_PERMISSION_DENIED.String(), fmt.Sprintf(format, args...))
}

//  内部错误
func IsInternalError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INTERNAL_ERROR.String() && e.Code == 500
}

//  内部错误
func ErrorInternalError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INTERNAL_ERROR.String(), fmt.Sprintf(format, args...))
}

// 发送用户不存在
func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 500
}

// 发送用户不存在
func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

//  目标用户数量过多
func IsTooManyTargets(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TOO_MANY_TARGETS.String() && e.Code == 500
}

//  目标用户数量过多
func ErrorTooManyTargets(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_TOO_MANY_TARGETS.String(), fmt.Sprintf(format, args...))
}

// 调用push service失败
func IsInvokePushFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVOKE_PUSH_FAILED.String() && e.Code == 500
}

// 调用push service失败
func ErrorInvokePushFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INVOKE_PUSH_FAILED.String(), fmt.Sprintf(format, args...))
}
