// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v5.28.2
// source: logic/v1/logic.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLogicServiceSendSystemPush = "/logic.v1.LogicService/SendSystemPush"

type LogicServiceHTTPServer interface {
	// SendSystemPush 系统主动推送（公告、通知）
	SendSystemPush(context.Context, *SystemPushRequest) (*SystemPushResponse, error)
}

func RegisterLogicServiceHTTPServer(s *http.Server, srv LogicServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/chatify/logic/v1/sendSystemPush", _LogicService_SendSystemPush0_HTTP_Handler(srv))
}

func _LogicService_SendSystemPush0_HTTP_Handler(srv LogicServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SystemPushRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLogicServiceSendSystemPush)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendSystemPush(ctx, req.(*SystemPushRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SystemPushResponse)
		return ctx.Result(200, reply)
	}
}

type LogicServiceHTTPClient interface {
	SendSystemPush(ctx context.Context, req *SystemPushRequest, opts ...http.CallOption) (rsp *SystemPushResponse, err error)
}

type LogicServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewLogicServiceHTTPClient(client *http.Client) LogicServiceHTTPClient {
	return &LogicServiceHTTPClientImpl{client}
}

func (c *LogicServiceHTTPClientImpl) SendSystemPush(ctx context.Context, in *SystemPushRequest, opts ...http.CallOption) (*SystemPushResponse, error) {
	var out SystemPushResponse
	pattern := "/chatify/logic/v1/sendSystemPush"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLogicServiceSendSystemPush))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
