// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: logic/v1/logic.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogicService_ValidateAndProcessMessage_FullMethodName = "/logic.v1.LogicService/ValidateAndProcessMessage"
	LogicService_SendSystemPush_FullMethodName            = "/logic.v1.LogicService/SendSystemPush"
)

// LogicServiceClient is the client API for LogicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogicServiceClient interface {
	// 接收原始消息，返回是否允许发送
	ValidateAndProcessMessage(ctx context.Context, in *ChatInputRequest, opts ...grpc.CallOption) (*ChatInputResponse, error)
	// 系统主动推送（公告、通知）
	SendSystemPush(ctx context.Context, in *SystemPushRequest, opts ...grpc.CallOption) (*SystemPushResponse, error)
}

type logicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogicServiceClient(cc grpc.ClientConnInterface) LogicServiceClient {
	return &logicServiceClient{cc}
}

func (c *logicServiceClient) ValidateAndProcessMessage(ctx context.Context, in *ChatInputRequest, opts ...grpc.CallOption) (*ChatInputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatInputResponse)
	err := c.cc.Invoke(ctx, LogicService_ValidateAndProcessMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicServiceClient) SendSystemPush(ctx context.Context, in *SystemPushRequest, opts ...grpc.CallOption) (*SystemPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemPushResponse)
	err := c.cc.Invoke(ctx, LogicService_SendSystemPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicServiceServer is the server API for LogicService service.
// All implementations must embed UnimplementedLogicServiceServer
// for forward compatibility.
type LogicServiceServer interface {
	// 接收原始消息，返回是否允许发送
	ValidateAndProcessMessage(context.Context, *ChatInputRequest) (*ChatInputResponse, error)
	// 系统主动推送（公告、通知）
	SendSystemPush(context.Context, *SystemPushRequest) (*SystemPushResponse, error)
	mustEmbedUnimplementedLogicServiceServer()
}

// UnimplementedLogicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogicServiceServer struct{}

func (UnimplementedLogicServiceServer) ValidateAndProcessMessage(context.Context, *ChatInputRequest) (*ChatInputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAndProcessMessage not implemented")
}
func (UnimplementedLogicServiceServer) SendSystemPush(context.Context, *SystemPushRequest) (*SystemPushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSystemPush not implemented")
}
func (UnimplementedLogicServiceServer) mustEmbedUnimplementedLogicServiceServer() {}
func (UnimplementedLogicServiceServer) testEmbeddedByValue()                      {}

// UnsafeLogicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogicServiceServer will
// result in compilation errors.
type UnsafeLogicServiceServer interface {
	mustEmbedUnimplementedLogicServiceServer()
}

func RegisterLogicServiceServer(s grpc.ServiceRegistrar, srv LogicServiceServer) {
	// If the following call pancis, it indicates UnimplementedLogicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogicService_ServiceDesc, srv)
}

func _LogicService_ValidateAndProcessMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).ValidateAndProcessMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_ValidateAndProcessMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).ValidateAndProcessMessage(ctx, req.(*ChatInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogicService_SendSystemPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServiceServer).SendSystemPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogicService_SendSystemPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServiceServer).SendSystemPush(ctx, req.(*SystemPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogicService_ServiceDesc is the grpc.ServiceDesc for LogicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logic.v1.LogicService",
	HandlerType: (*LogicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAndProcessMessage",
			Handler:    _LogicService_ValidateAndProcessMessage_Handler,
		},
		{
			MethodName: "SendSystemPush",
			Handler:    _LogicService_SendSystemPush_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic/v1/logic.proto",
}
