// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsOk(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OK.String() && e.Code == 200
}

func ErrorOk(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_OK.String(), fmt.Sprintf(format, args...))
}

// 用户名重复
func IsUsernameRepeat(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USERNAME_REPEAT.String() && e.Code == 500
}

// 用户名重复
func ErrorUsernameRepeat(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USERNAME_REPEAT.String(), fmt.Sprintf(format, args...))
}

// 消息数量过多
func IsTooManyMessages(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TOO_MANY_MESSAGES.String() && e.Code == 500
}

// 消息数量过多
func ErrorTooManyMessages(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_TOO_MANY_MESSAGES.String(), fmt.Sprintf(format, args...))
}

// 保存消息失败
func IsSaveMessageFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SAVE_MESSAGE_FAILED.String() && e.Code == 500
}

// 保存消息失败
func ErrorSaveMessageFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SAVE_MESSAGE_FAILED.String(), fmt.Sprintf(format, args...))
}

// 离线消息归档失败
func IsArchiveOfflineMessageFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ARCHIVE_OFFLINE_MESSAGE_FAILED.String() && e.Code == 500
}

// 离线消息归档失败
func ErrorArchiveOfflineMessageFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_ARCHIVE_OFFLINE_MESSAGE_FAILED.String(), fmt.Sprintf(format, args...))
}

// 更新消息状态失败
func IsUpdateMessageStatusFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UPDATE_MESSAGE_STATUS_FAILED.String() && e.Code == 500
}

// 更新消息状态失败
func ErrorUpdateMessageStatusFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UPDATE_MESSAGE_STATUS_FAILED.String(), fmt.Sprintf(format, args...))
}
