// Code generated by Wire. DO NOT EDIT.

//go:generate go run  github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"push/internal/biz"
	"push/internal/conf"
	"push/internal/data"
	"push/internal/server"
	"push/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	push := biz.NewPush(logger, userRepo)
	pushService := service.NewPushService(push)
	grpcServer := server.NewGRPCServer(bootstrap, pushService, logger)
	client, err := data.NewEtcdClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	registrar := data.NewRegistry(client)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
