// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"push/internal/biz"
	"push/internal/conf"
	"push/internal/data"
	"push/internal/server"
	"push/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	sessionRepo := data.NewSessionRepo(dataData, logger)
	messageRepo := data.NewMessageRepo(dataData, logger)
	client, err := data.NewEtcdClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	discovery := data.NewDiscovery(client)
	accessNodeManager, cleanup2, err := data.NewAccessNodeManager(discovery, dataData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	push := biz.NewPush(logger, sessionRepo, messageRepo, accessNodeManager)
	pushService := service.NewPushService(push, logger)
	grpcServer := server.NewGRPCServer(bootstrap, pushService, logger)
	httpServer := server.NewHTTPServer(bootstrap, pushService, logger)
	registrar := data.NewRegistry(client)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
