// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/xinghe903/chatify/push/internal/biz"
	"github.com/xinghe903/chatify/push/internal/conf"
	"github.com/xinghe903/chatify/push/internal/data"
	"github.com/xinghe903/chatify/push/internal/server"
	"github.com/xinghe903/chatify/push/internal/service"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	sessionRepo := data.NewSessionRepo(dataData, logger)
	messageRepo := data.NewMessageRepo(dataData, logger)
	client, err := data.NewEtcdClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	discovery := data.NewDiscovery(client)
	accessNodeManager, cleanup2, err := data.NewAccessNodeManager(bootstrap, discovery, dataData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	offlineRepo, cleanup3 := data.NewOfflineClient(bootstrap, logger, discovery)
	push := biz.NewPush(logger, sessionRepo, messageRepo, accessNodeManager, offlineRepo)
	consumer, cleanup4 := data.NewKafkaConsumer(bootstrap, logger)
	messageDedupRepo := data.NewMessageDedupRepo(dataData, logger)
	userStateHandler, cleanup5 := biz.NewUserStateHandler(logger, offlineRepo, accessNodeManager, consumer, messageDedupRepo)
	pushService := service.NewPushService(push, logger, userStateHandler)
	grpcServer := server.NewGRPCServer(bootstrap, pushService, logger)
	httpServer := server.NewHTTPServer(bootstrap, pushService, logger)
	registrar := data.NewRegistry(client)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
