// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsOk(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OK.String() && e.Code == 200
}

func ErrorOk(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_OK.String(), fmt.Sprintf(format, args...))
}

// 消息重复
func IsMessageRepeat(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MESSAGE_REPEAT.String() && e.Code == 500
}

// 消息重复
func ErrorMessageRepeat(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_MESSAGE_REPEAT.String(), fmt.Sprintf(format, args...))
}

// 无效用户
func IsInvalidUser(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_USER.String() && e.Code == 500
}

// 无效用户
func ErrorInvalidUser(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INVALID_USER.String(), fmt.Sprintf(format, args...))
}

// 消息过多
func IsTooManyMessages(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TOO_MANY_MESSAGES.String() && e.Code == 500
}

// 消息过多
func ErrorTooManyMessages(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_TOO_MANY_MESSAGES.String(), fmt.Sprintf(format, args...))
}

// 存档消息失败
func IsArchiveMessageFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ARCHIVE_MESSAGE_FAILED.String() && e.Code == 500
}

// 存档消息失败
func ErrorArchiveMessageFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_ARCHIVE_MESSAGE_FAILED.String(), fmt.Sprintf(format, args...))
}

// 获取离线消息失败
func IsGetOfflineMessageFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GET_OFFLINE_MESSAGE_FAILED.String() && e.Code == 500
}

// 获取离线消息失败
func ErrorGetOfflineMessageFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_GET_OFFLINE_MESSAGE_FAILED.String(), fmt.Sprintf(format, args...))
}

// 标记消息为已送达失败
func IsMarkMessageAsDeliveredFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_MARK_MESSAGE_AS_DELIVERED_FAILED.String() && e.Code == 500
}

// 标记消息为已送达失败
func ErrorMarkMessageAsDeliveredFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_MARK_MESSAGE_AS_DELIVERED_FAILED.String(), fmt.Sprintf(format, args...))
}
