// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: offline/v1/offline.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OfflineService_RetrieveOfflineMessages_FullMethodName = "/offline.v1.OfflineService/RetrieveOfflineMessages"
	OfflineService_AcknowledgeMessages_FullMethodName     = "/offline.v1.OfflineService/AcknowledgeMessages"
	OfflineService_ArchiveMessages_FullMethodName         = "/offline.v1.OfflineService/ArchiveMessages"
)

// OfflineServiceClient is the client API for OfflineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OfflineServiceClient interface {
	// 主动拉取离线消息（用户上线时）
	RetrieveOfflineMessages(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error)
	// 确认一批消息已送达（由 Push 调用）
	AcknowledgeMessages(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error)
	// 归档一批离线消息
	ArchiveMessages(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error)
}

type offlineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOfflineServiceClient(cc grpc.ClientConnInterface) OfflineServiceClient {
	return &offlineServiceClient{cc}
}

func (c *offlineServiceClient) RetrieveOfflineMessages(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveResponse)
	err := c.cc.Invoke(ctx, OfflineService_RetrieveOfflineMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offlineServiceClient) AcknowledgeMessages(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, OfflineService_AcknowledgeMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offlineServiceClient) ArchiveMessages(ctx context.Context, in *ArchiveRequest, opts ...grpc.CallOption) (*ArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveResponse)
	err := c.cc.Invoke(ctx, OfflineService_ArchiveMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfflineServiceServer is the server API for OfflineService service.
// All implementations must embed UnimplementedOfflineServiceServer
// for forward compatibility.
type OfflineServiceServer interface {
	// 主动拉取离线消息（用户上线时）
	RetrieveOfflineMessages(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
	// 确认一批消息已送达（由 Push 调用）
	AcknowledgeMessages(context.Context, *AckRequest) (*AckResponse, error)
	// 归档一批离线消息
	ArchiveMessages(context.Context, *ArchiveRequest) (*ArchiveResponse, error)
	mustEmbedUnimplementedOfflineServiceServer()
}

// UnimplementedOfflineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOfflineServiceServer struct{}

func (UnimplementedOfflineServiceServer) RetrieveOfflineMessages(context.Context, *RetrieveRequest) (*RetrieveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveOfflineMessages not implemented")
}
func (UnimplementedOfflineServiceServer) AcknowledgeMessages(context.Context, *AckRequest) (*AckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeMessages not implemented")
}
func (UnimplementedOfflineServiceServer) ArchiveMessages(context.Context, *ArchiveRequest) (*ArchiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveMessages not implemented")
}
func (UnimplementedOfflineServiceServer) mustEmbedUnimplementedOfflineServiceServer() {}
func (UnimplementedOfflineServiceServer) testEmbeddedByValue()                        {}

// UnsafeOfflineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OfflineServiceServer will
// result in compilation errors.
type UnsafeOfflineServiceServer interface {
	mustEmbedUnimplementedOfflineServiceServer()
}

func RegisterOfflineServiceServer(s grpc.ServiceRegistrar, srv OfflineServiceServer) {
	// If the following call pancis, it indicates UnimplementedOfflineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OfflineService_ServiceDesc, srv)
}

func _OfflineService_RetrieveOfflineMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfflineServiceServer).RetrieveOfflineMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfflineService_RetrieveOfflineMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfflineServiceServer).RetrieveOfflineMessages(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfflineService_AcknowledgeMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfflineServiceServer).AcknowledgeMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfflineService_AcknowledgeMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfflineServiceServer).AcknowledgeMessages(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfflineService_ArchiveMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfflineServiceServer).ArchiveMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfflineService_ArchiveMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfflineServiceServer).ArchiveMessages(ctx, req.(*ArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OfflineService_ServiceDesc is the grpc.ServiceDesc for OfflineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OfflineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "offline.v1.OfflineService",
	HandlerType: (*OfflineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveOfflineMessages",
			Handler:    _OfflineService_RetrieveOfflineMessages_Handler,
		},
		{
			MethodName: "AcknowledgeMessages",
			Handler:    _OfflineService_AcknowledgeMessages_Handler,
		},
		{
			MethodName: "ArchiveMessages",
			Handler:    _OfflineService_ArchiveMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "offline/v1/offline.proto",
}
