// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.0
// - protoc             v5.28.2
// source: offline/v1/offline.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationOfflineServiceAcknowledgeMessages = "/offline.v1.OfflineService/AcknowledgeMessages"
const OperationOfflineServiceArchiveMessages = "/offline.v1.OfflineService/ArchiveMessages"
const OperationOfflineServiceRetrieveOfflineMessages = "/offline.v1.OfflineService/RetrieveOfflineMessages"

type OfflineServiceHTTPServer interface {
	// AcknowledgeMessages 确认一批消息已送达（由 Push 调用）
	AcknowledgeMessages(context.Context, *AckRequest) (*AckResponse, error)
	// ArchiveMessages 归档一批离线消息
	ArchiveMessages(context.Context, *ArchiveRequest) (*ArchiveResponse, error)
	// RetrieveOfflineMessages 主动拉取离线消息（用户上线时）
	RetrieveOfflineMessages(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
}

func RegisterOfflineServiceHTTPServer(s *http.Server, srv OfflineServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/chatify/offline/v1/RetrieveOfflineMessages", _OfflineService_RetrieveOfflineMessages0_HTTP_Handler(srv))
	r.POST("/chatify/offline/v1/AcknowledgeMessages", _OfflineService_AcknowledgeMessages0_HTTP_Handler(srv))
	r.POST("/chatify/offline/v1/ArchiveMessages", _OfflineService_ArchiveMessages0_HTTP_Handler(srv))
}

func _OfflineService_RetrieveOfflineMessages0_HTTP_Handler(srv OfflineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RetrieveRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOfflineServiceRetrieveOfflineMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RetrieveOfflineMessages(ctx, req.(*RetrieveRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RetrieveResponse)
		return ctx.Result(200, reply)
	}
}

func _OfflineService_AcknowledgeMessages0_HTTP_Handler(srv OfflineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AckRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOfflineServiceAcknowledgeMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AcknowledgeMessages(ctx, req.(*AckRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AckResponse)
		return ctx.Result(200, reply)
	}
}

func _OfflineService_ArchiveMessages0_HTTP_Handler(srv OfflineServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArchiveRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOfflineServiceArchiveMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ArchiveMessages(ctx, req.(*ArchiveRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ArchiveResponse)
		return ctx.Result(200, reply)
	}
}

type OfflineServiceHTTPClient interface {
	AcknowledgeMessages(ctx context.Context, req *AckRequest, opts ...http.CallOption) (rsp *AckResponse, err error)
	ArchiveMessages(ctx context.Context, req *ArchiveRequest, opts ...http.CallOption) (rsp *ArchiveResponse, err error)
	RetrieveOfflineMessages(ctx context.Context, req *RetrieveRequest, opts ...http.CallOption) (rsp *RetrieveResponse, err error)
}

type OfflineServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOfflineServiceHTTPClient(client *http.Client) OfflineServiceHTTPClient {
	return &OfflineServiceHTTPClientImpl{client}
}

func (c *OfflineServiceHTTPClientImpl) AcknowledgeMessages(ctx context.Context, in *AckRequest, opts ...http.CallOption) (*AckResponse, error) {
	var out AckResponse
	pattern := "/chatify/offline/v1/AcknowledgeMessages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOfflineServiceAcknowledgeMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OfflineServiceHTTPClientImpl) ArchiveMessages(ctx context.Context, in *ArchiveRequest, opts ...http.CallOption) (*ArchiveResponse, error) {
	var out ArchiveResponse
	pattern := "/chatify/offline/v1/ArchiveMessages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationOfflineServiceArchiveMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *OfflineServiceHTTPClientImpl) RetrieveOfflineMessages(ctx context.Context, in *RetrieveRequest, opts ...http.CallOption) (*RetrieveResponse, error) {
	var out RetrieveResponse
	pattern := "/chatify/offline/v1/RetrieveOfflineMessages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationOfflineServiceRetrieveOfflineMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
