// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.4
// source: service/v1/service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReq) Reset() {
	*x = ChatReq{}
	mi := &file_service_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReq) ProtoMessage() {}

func (x *ChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReq.ProtoReflect.Descriptor instead.
func (*ChatReq) Descriptor() ([]byte, []int) {
	return file_service_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChatReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChatRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRsp) Reset() {
	*x = ChatRsp{}
	mi := &file_service_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRsp) ProtoMessage() {}

func (x *ChatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRsp.ProtoReflect.Descriptor instead.
func (*ChatRsp) Descriptor() ([]byte, []int) {
	return file_service_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_service_v1_service_proto protoreflect.FileDescriptor

const file_service_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18service/v1/service.proto\x12\n" +
	"service.v1\x1a\x1cgoogle/api/annotations.proto\"\x1d\n" +
	"\aChatReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"#\n" +
	"\aChatRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2?\n" +
	"\aService\x124\n" +
	"\x04Chat\x12\x13.service.v1.ChatReq\x1a\x13.service.v1.ChatRsp(\x010\x01B\x13Z\x11api/service/v1;v1b\x06proto3"

var (
	file_service_v1_service_proto_rawDescOnce sync.Once
	file_service_v1_service_proto_rawDescData []byte
)

func file_service_v1_service_proto_rawDescGZIP() []byte {
	file_service_v1_service_proto_rawDescOnce.Do(func() {
		file_service_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_v1_service_proto_rawDesc), len(file_service_v1_service_proto_rawDesc)))
	})
	return file_service_v1_service_proto_rawDescData
}

var file_service_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_v1_service_proto_goTypes = []any{
	(*ChatReq)(nil), // 0: service.v1.ChatReq
	(*ChatRsp)(nil), // 1: service.v1.ChatRsp
}
var file_service_v1_service_proto_depIdxs = []int32{
	0, // 0: service.v1.Service.Chat:input_type -> service.v1.ChatReq
	1, // 1: service.v1.Service.Chat:output_type -> service.v1.ChatRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_v1_service_proto_init() }
func file_service_v1_service_proto_init() {
	if File_service_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_v1_service_proto_rawDesc), len(file_service_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_v1_service_proto_goTypes,
		DependencyIndexes: file_service_v1_service_proto_depIdxs,
		MessageInfos:      file_service_v1_service_proto_msgTypes,
	}.Build()
	File_service_v1_service_proto = out.File
	file_service_v1_service_proto_goTypes = nil
	file_service_v1_service_proto_depIdxs = nil
}
