// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"logic/internal/biz"
	"logic/internal/conf"
	"logic/internal/data"
	"logic/internal/server"
	"logic/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	client, err := data.NewEtcdClient(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	discovery := data.NewDiscovery(client)
	pushRepo, cleanup := data.NewPushServiceClient(bootstrap, logger, discovery)
	logic := biz.NewLogic(logger, pushRepo, bootstrap)
	consumer, cleanup2 := data.NewKafkaConsumer(bootstrap, logger)
	dataData, cleanup3, err := data.NewData(bootstrap, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	messageDedupRepo := data.NewMessageDedupRepo(dataData, logger)
	mqProducer, cleanup4, err := data.NewKafkaProducer(bootstrap, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userMessageHandler, cleanup5 := biz.NewUserMessageHandler(logger, consumer, messageDedupRepo, mqProducer)
	logicService := service.NewLogicService(logic, logger, userMessageHandler)
	httpServer := server.NewHTTPServer(bootstrap, logicService, logger)
	grpcServer := server.NewGRPCServer(bootstrap, logicService, logger)
	registrar := data.NewRegistry(client)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
