// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsOk(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OK.String() && e.Code == 200
}

func ErrorOk(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_OK.String(), fmt.Sprintf(format, args...))
}

// 用户名重复
func IsUsernameRepeat(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USERNAME_REPEAT.String() && e.Code == 500
}

// 用户名重复
func ErrorUsernameRepeat(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USERNAME_REPEAT.String(), fmt.Sprintf(format, args...))
}

// 用户不存在
func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 500
}

// 用户不存在
func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 用户被禁用
func IsUserDisabled(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_DISABLED.String() && e.Code == 500
}

// 用户被禁用
func ErrorUserDisabled(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USER_DISABLED.String(), fmt.Sprintf(format, args...))
}

// 用户名无效
func IsUserNameInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NAME_INVALID.String() && e.Code == 500
}

// 用户名无效
func ErrorUserNameInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USER_NAME_INVALID.String(), fmt.Sprintf(format, args...))
}

// 密码无效
func IsPasswordInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PASSWORD_INVALID.String() && e.Code == 500
}

// 密码无效
func ErrorPasswordInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_PASSWORD_INVALID.String(), fmt.Sprintf(format, args...))
}

// 用户名或密码无效
func IsNameOrPasswordInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NAME_OR_PASSWORD_INVALID.String() && e.Code == 500
}

// 用户名或密码无效
func ErrorNameOrPasswordInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_NAME_OR_PASSWORD_INVALID.String(), fmt.Sprintf(format, args...))
}

// 生成ID失败
func IsGenerateIdFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GENERATE_ID_FAILED.String() && e.Code == 500
}

// 生成ID失败
func ErrorGenerateIdFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_GENERATE_ID_FAILED.String(), fmt.Sprintf(format, args...))
}

// 用户状态无效
func IsUserStatusInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_STATUS_INVALID.String() && e.Code == 500
}

// 用户状态无效
func ErrorUserStatusInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USER_STATUS_INVALID.String(), fmt.Sprintf(format, args...))
}

// 邮箱无效
func IsEmailInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_EMAIL_INVALID.String() && e.Code == 500
}

// 邮箱无效
func ErrorEmailInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_EMAIL_INVALID.String(), fmt.Sprintf(format, args...))
}

// 手机号无效
func IsPhoneInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PHONE_INVALID.String() && e.Code == 500
}

// 手机号无效
func ErrorPhoneInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_PHONE_INVALID.String(), fmt.Sprintf(format, args...))
}

// 密码加密失败
func IsPasswordBcryptFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PASSWORD_BCRYPT_FAILED.String() && e.Code == 500
}

// 密码加密失败
func ErrorPasswordBcryptFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_PASSWORD_BCRYPT_FAILED.String(), fmt.Sprintf(format, args...))
}

// 创建用户失败
func IsCreateUserFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CREATE_USER_FAILED.String() && e.Code == 500
}

// 创建用户失败
func ErrorCreateUserFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CREATE_USER_FAILED.String(), fmt.Sprintf(format, args...))
}

// 令牌无效
func IsTokenInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TOKEN_INVALID.String() && e.Code == 500
}

// 令牌无效
func ErrorTokenInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_TOKEN_INVALID.String(), fmt.Sprintf(format, args...))
}

// 保存会话失败
func IsSaveSessionFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SAVE_SESSION_FAILED.String() && e.Code == 500
}

// 保存会话失败
func ErrorSaveSessionFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SAVE_SESSION_FAILED.String(), fmt.Sprintf(format, args...))
}

// 参数无效
func IsParamInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PARAM_INVALID.String() && e.Code == 500
}

// 参数无效
func ErrorParamInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_PARAM_INVALID.String(), fmt.Sprintf(format, args...))
}

// 清除会话失败
func IsClearSessionFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CLEAR_SESSION_FAILED.String() && e.Code == 500
}

// 清除会话失败
func ErrorClearSessionFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CLEAR_SESSION_FAILED.String(), fmt.Sprintf(format, args...))
}

// 用户状态未激活
func IsUserStatusNotActive(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_STATUS_NOT_ACTIVE.String() && e.Code == 500
}

// 用户状态未激活
func ErrorUserStatusNotActive(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USER_STATUS_NOT_ACTIVE.String(), fmt.Sprintf(format, args...))
}

// 撤销用户失败
func IsRevokeUserFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVOKE_USER_FAILED.String() && e.Code == 500
}

// 撤销用户失败
func ErrorRevokeUserFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_REVOKE_USER_FAILED.String(), fmt.Sprintf(format, args...))
}

// 刷新令牌失败
func IsRefreshTokenFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REFRESH_TOKEN_FAILED.String() && e.Code == 500
}

// 刷新令牌失败
func ErrorRefreshTokenFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_REFRESH_TOKEN_FAILED.String(), fmt.Sprintf(format, args...))
}

// 验证令牌失败
func IsVerifyTokenFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_VERIFY_TOKEN_FAILED.String() && e.Code == 500
}

// 验证令牌失败
func ErrorVerifyTokenFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_VERIFY_TOKEN_FAILED.String(), fmt.Sprintf(format, args...))
}
