// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsOk(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_OK.String() && e.Code == 200
}

func ErrorOk(format string, args ...interface{}) *errors.Error {
	return errors.New(200, ErrorReason_OK.String(), fmt.Sprintf(format, args...))
}

// 用户名重复
func IsUsernameRepeat(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USERNAME_REPEAT.String() && e.Code == 500
}

// 用户名重复
func ErrorUsernameRepeat(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USERNAME_REPEAT.String(), fmt.Sprintf(format, args...))
}

// 连接不存在
func IsConnectionNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CONNECTION_NOT_FOUND.String() && e.Code == 500
}

// 连接不存在
func ErrorConnectionNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_CONNECTION_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 部分消息发送失败
func IsPartialMessageFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PARTIAL_MESSAGE_FAILED.String() && e.Code == 500
}

// 部分消息发送失败
func ErrorPartialMessageFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_PARTIAL_MESSAGE_FAILED.String(), fmt.Sprintf(format, args...))
}

// 所有消息发送失败
func IsAllMessageFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ALL_MESSAGE_FAILED.String() && e.Code == 500
}

// 所有消息发送失败
func ErrorAllMessageFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_ALL_MESSAGE_FAILED.String(), fmt.Sprintf(format, args...))
}

// 服务器内部错误
func IsInternalServerError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INTERNAL_SERVER_ERROR.String() && e.Code == 500
}

// 服务器内部错误
func ErrorInternalServerError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INTERNAL_SERVER_ERROR.String(), fmt.Sprintf(format, args...))
}

// 非法消息
func IsInvalidMessage(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_MESSAGE.String() && e.Code == 500
}

// 非法消息
func ErrorInvalidMessage(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INVALID_MESSAGE.String(), fmt.Sprintf(format, args...))
}

// 用户不存在
func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 500
}

// 用户不存在
func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
